package com.chatbot.chatbot.repository;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.List;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.test.context.ActiveProfiles;

import com.chatbot.chatbot.entity.ChatSession;
import com.chatbot.chatbot.entity.Message;
import com.chatbot.chatbot.entity.Role;
import com.chatbot.chatbot.entity.User;
import com.chatbot.chatbot.enums.ChatStatus;
import com.chatbot.chatbot.enums.MessageStatus;

/**
 * Repository Integration Tests for MessageRepository
 *
 * Uses @DataJpaTest which provides an in-memory H2 database.
 * Tests actual SQL queries generated by Spring Data JPA.
 *
 * NOTE: Requires H2 dependency or test profile with embedded DB.
 * If MySQL-only is required, annotate with @AutoConfigureTestDatabase(replace = NONE)
 * and use a test MySQL config.
 */
@DataJpaTest
@ActiveProfiles("test")
@DisplayName("MessageRepository Integration Tests")
class MessageRepositoryTest {

    @Autowired
    private MessageRepository messageRepository;

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private ChatSessionRepository chatSessionRepository;

    @Autowired
    private RoleRepository roleRepository;

    private User customer;
    private User agent;
    private ChatSession chatSession;

    @BeforeEach
    void setUp() {
        messageRepository.deleteAll();
        chatSessionRepository.deleteAll();
        userRepository.deleteAll();
        roleRepository.deleteAll();

        Role customerRole = new Role("CUSTOMER", "Customer role");
        Role agentRole    = new Role("AGENT", "Agent role");
        roleRepository.save(customerRole);
        roleRepository.save(agentRole);

        customer = new User();
        customer.setFirstName("John");
        customer.setLastName("Doe");
        customer.setEmail("john@test.com");
        customer.setPassword("password");
        customer.setRole(customerRole);
        customer.setActive(true);
        userRepository.save(customer);

        agent = new User();
        agent.setFirstName("Agent");
        agent.setLastName("Smith");
        agent.setEmail("agent@test.com");
        agent.setPassword("password");
        agent.setRole(agentRole);
        agent.setActive(true);
        userRepository.save(agent);

        chatSession = new ChatSession();
        chatSession.setStatus(ChatStatus.ACTIVE);
        chatSession.setCustomer(customer);
        chatSession.setAgent(agent);
        chatSessionRepository.save(chatSession);
    }

    private Message createMessage(User sender, String content, MessageStatus status) {
        Message msg = new Message();
        msg.setContent(content);
        msg.setStatus(status);
        msg.setSender(sender);
        msg.setChatSession(chatSession);
        return messageRepository.save(msg);
    }

    @Test
    @DisplayName("findByChatSessionId: should return paginated messages")
    void findByChatSessionId_ReturnsPaginatedMessages() {
        createMessage(customer, "Message 1", MessageStatus.SENT);
        createMessage(agent,    "Message 2", MessageStatus.DELIVERED);
        createMessage(customer, "Message 3", MessageStatus.READ);

        Pageable pageable = PageRequest.of(0, 20);
        Page<Message> result = messageRepository.findByChatSessionId(chatSession.getId(), pageable);

        assertThat(result.getTotalElements()).isEqualTo(3);
        assertThat(result.getContent()).hasSize(3);
    }

    @Test
    @DisplayName("findByChatSessionId: should respect page size")
    void findByChatSessionId_RespectsPageSize() {
        for (int i = 1; i <= 5; i++) {
            createMessage(customer, "Message " + i, MessageStatus.SENT);
        }

        Pageable pageable = PageRequest.of(0, 2);
        Page<Message> page0 = messageRepository.findByChatSessionId(chatSession.getId(), pageable);

        assertThat(page0.getContent()).hasSize(2);
        assertThat(page0.getTotalElements()).isEqualTo(5);
        assertThat(page0.getTotalPages()).isEqualTo(3);
    }

    @Test
    @DisplayName("countUnreadMessages: should count messages not sent by userId and not READ")
    void countUnreadMessages_ReturnsCorrectCount() {
        createMessage(agent,    "Agent msg 1",   MessageStatus.SENT);
        createMessage(agent,    "Agent msg 2",   MessageStatus.DELIVERED);
        createMessage(agent,    "Agent msg read",MessageStatus.READ);
        createMessage(customer, "Customer msg",  MessageStatus.SENT);

        // Customer's unread = agent messages not READ = 2
        Long unread = messageRepository.countUnreadMessages(chatSession.getId(), customer.getId());
        assertThat(unread).isEqualTo(2L);
    }

    @Test
    @DisplayName("findUnreadMessages: should return messages not sent by user and not READ")
    void findUnreadMessages_ReturnsUnreadMessages() {
        createMessage(agent,    "Unread 1",    MessageStatus.SENT);
        createMessage(agent,    "Unread 2",    MessageStatus.DELIVERED);
        createMessage(agent,    "Already read",MessageStatus.READ);
        createMessage(customer, "Own message", MessageStatus.SENT);

        List<Message> unread = messageRepository.findUnreadMessages(
                chatSession.getId(), customer.getId());

        assertThat(unread).hasSize(2);
        unread.forEach(m -> assertThat(m.getStatus()).isNotEqualTo(MessageStatus.READ));
        unread.forEach(m -> assertThat(m.getSender().getId()).isNotEqualTo(customer.getId()));
    }

    @Test
    @DisplayName("countByChatSessionId: should return total message count")
    void countByChatSessionId_ReturnsTotalCount() {
        createMessage(customer, "M1", MessageStatus.SENT);
        createMessage(agent,    "M2", MessageStatus.DELIVERED);

        Long count = messageRepository.countByChatSessionId(chatSession.getId());
        assertThat(count).isEqualTo(2L);
    }

    @Test
    @DisplayName("findByChatSessionIdAndStatus: should filter by status")
    void findByChatSessionIdAndStatus_ReturnsFilteredMessages() {
        createMessage(customer, "Sent 1",    MessageStatus.SENT);
        createMessage(customer, "Sent 2",    MessageStatus.SENT);
        createMessage(customer, "Delivered", MessageStatus.DELIVERED);
        createMessage(agent,    "Read",      MessageStatus.READ);

        List<Message> sentMessages = messageRepository.findByChatSessionIdAndStatus(
                chatSession.getId(), MessageStatus.SENT);

        assertThat(sentMessages).hasSize(2);
        sentMessages.forEach(m -> assertThat(m.getStatus()).isEqualTo(MessageStatus.SENT));
    }

    @Test
    @DisplayName("findByChatSessionIdOrderBySentAtAsc: should return ordered messages")
    void findByChatSessionIdOrderBySentAtAsc_ReturnsOrdered() throws InterruptedException {
        Message m1 = createMessage(customer, "First",  MessageStatus.SENT);
        Thread.sleep(10);
        Message m2 = createMessage(agent,    "Second", MessageStatus.SENT);
        Thread.sleep(10);
        Message m3 = createMessage(customer, "Third",  MessageStatus.SENT);

        List<Message> ordered = messageRepository.findByChatSessionIdOrderBySentAtAsc(chatSession.getId());

        assertThat(ordered).hasSize(3);
        assertThat(ordered.get(0).getContent()).isEqualTo("First");
        assertThat(ordered.get(1).getContent()).isEqualTo("Second");
        assertThat(ordered.get(2).getContent()).isEqualTo("Third");
    }

    @Test
    @DisplayName("Empty session: should return empty results")
    void emptySession_ReturnsEmpty() {
        ChatSession emptySession = new ChatSession();
        emptySession.setStatus(ChatStatus.WAITING);
        emptySession.setCustomer(customer);
        chatSessionRepository.save(emptySession);

        Pageable pageable = PageRequest.of(0, 20);
        Page<Message> result = messageRepository.findByChatSessionId(emptySession.getId(), pageable);

        assertThat(result.getTotalElements()).isEqualTo(0);
        assertThat(result.getContent()).isEmpty();
    }
}
